name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # можно заменить на любую ветку, например, если у тебя ветка "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set token in JS file
        run: |
          sed -i 's/{{telegram_token}}/${{ secrets.BOT_TOKEN }}/g' ipapi.js
          
